name: first composite action
description: learning about composite actions
runs:
  using: 'composite'
  steps:
  - name: step1
    run: echo "this is my first composite action"
    shell: bash
  - name: step2
    run: echo "this is my second action"
    shell: bash
