# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo "step1 from job1"

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo step2 from job1.

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo "step1 from job2"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo step2 from job2.
