# This is a basic workflow to help you get started with Actions

name: environment variables

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  var1: 20
  name: anusha

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: custom environment variables
        run: |
          echo $var1
          echo ${{env.var1}}
          echo ${{env.name}}
